# Generated by Django 3.2.9 on 2021-11-24 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systemSet', '0002_auto_20211124_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_active', models.BooleanField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemSet.area')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemSet.rolemanage')),
            ],
        ),
    ]
