# Generated by Django 3.2.9 on 2021-11-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=1, verbose_name='状态'),
        ),
    ]
