# Generated by Django 3.2.9 on 2021-11-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
