# Generated by Django 3.2.9 on 2021-11-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态'),
        ),
    ]
