# Generated by Django 3.2.9 on 2021-11-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.CharField(default='启用', max_length=2, verbose_name='状态'),
        ),
    ]
