# Generated by Django 3.2.9 on 2021-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSet', '0002_auto_20211124_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='is_activ',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='area',
            name='areaCode',
            field=models.CharField(max_length=11, unique=True, verbose_name='区划代码'),
        ),
    ]
