# Generated by Django 3.2.9 on 2021-11-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemSet', '0003_auto_20211124_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '区划管理', 'verbose_name_plural': '区划管理'},
        ),
        migrations.AlterModelOptions(
            name='rolemanage',
            options={'verbose_name': '角色管理', 'verbose_name_plural': '角色管理'},
        ),
    ]
