# Generated by Django 3.2.9 on 2021-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemSet', '0004_auto_20211124_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaName',
            field=models.CharField(max_length=11, unique=True, verbose_name='所属区域'),
        ),
    ]
